### ISSUE TITLE
_io.py "cannot import name 'object' from 'numpy'

### ISSUE THREAD

**Issue by smoussally** [pikipity/Toolbox-for-Adaptive-Fourier-Decomposition#13]
The first line in file `_io.py`
`from numpy import ndarray, object` creates an importation error when running sample codes.
`ImportError: cannot import name 'object' from 'numpy'`
Removing the import of module `object` solves the issue.

**Comment by pikipity** [comment]
Sorry for replying you late. I do not suggest you removing "object" because such operation will make some functions error. You can use numpy v1.23. In the later version, we will try to fix this problem
